# Generated by Django 4.1.1 on 2023-05-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_libraryimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.post'),
        ),
    ]
