# Generated by Django 4.1.1 on 2023-06-03 13:30

from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_libraryimages_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryImagesClassified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=journal.models.image_upload_path_classified)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.libraryimages')),
            ],
        ),
    ]
