# Generated by Django 4.1.1 on 2023-06-04 14:56

from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_libraryimagesclassified'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAudioFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=journal.models.audio_upload_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.post')),
            ],
        ),
    ]
