# Generated by Django 4.1.1 on 2023-06-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_libraryaudiofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAudioFilesClassified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_result', models.CharField(max_length=100)),
                ('original_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.libraryaudiofiles')),
            ],
        ),
    ]
