# Generated by Django 4.1.1 on 2023-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_libraryaudiofilesclassified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='public', max_length=100),
        ),
    ]
